title: About me! - Zuzanna Konopka
description: Education, skills, hobby and few facts about me!

preferences:
    name: language
    options:
      - label: English
        value: en
      - label: Polish
        value: pl
        
remote_theme: pages-themes/merlot@v0.2.0
plugins:
- jekyll-remote-theme

gem "github-pages", group: :jekyll_plugins

